backend:
  name: github
  repo: sarthakveggalam/hugo-restaurant-tutorial
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/gallery"  #folder where user uploaded files should go

collections:
  - name: Food
    label: "Food Item"     #used in the UI i.e. "New Post"
    folder: "site/content/food"   # the path to the folder where the contents are stored
    create: true    #Allow users to create new documents in this selection
    fields: #the fields for each document in this collection have
      - {label: "Name of Item", name:"title", widget:"string"}
      - {label: "Supported Meals", name:"categories", widget:"list", default: ["lunch","dinner"]}
      - {label: "Price", name: "price", widget: "string"}
